const CONFIG_FILENAME = './config.json';
const SQLITE_FILENAME = './records.db';
const PURPOSE_INNER = 'INNER';
const PURPOSE_OUTER = 'OUTER';
const PURPOSE_WATER = 'WATER';
const PURPOSE_NONE = 'NONE';

module.exports = {
  CONFIG_FILENAME,
  SQLITE_FILENAME,
  PURPOSE_INNER,
  PURPOSE_OUTER,
  PURPOSE_WATER,
  PURPOSE_NONE,
};
